#!/usr/bin/env python3
"""Build animatic/timing.json (the ONLY timing the animatic reads) from a voice timeline.

    python3 src/make_timing.py [../out/voice-v31/timeline.json]

Input: the VOICE timeline (events: sentence {n, scene, start_s, end_s, text} and pause {kind, start_s, end_s}).
When the narration is regenerated, point this at the new timeline.json, run it, then re-render (render_all.sh):
every picture action is anchored to a sentence number + keyword in anchors.json, so it moves with the voice.
Scene cut = LEAD s before the scene's first sentence (picture leads the voice); the first scene starts at 0, the last
ends at the timeline's total_s. Sentence numbers must match script-v3.1 (105 sentences, S01..S20)."""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
AN = os.path.dirname(HERE)
EP = os.path.dirname(AN)
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(EP, 'out', 'voice-v31', 'timeline.json')
tl = json.load(open(src))
LEAD = 0.35
sent = [e for e in tl['events'] if e['type'] == 'sentence']
pauses = [e for e in tl['events'] if e['type'] == 'pause']
order = []
for e in sent:
    if e['scene'] not in order:
        order.append(e['scene'])
assert order == [f'S{i:02d}' for i in range(1, 21)], order
assert [e['n'] for e in sent] == list(range(1, len(sent) + 1))
scenes = []
for i, sid in enumerate(order):
    ss = [e for e in sent if e['scene'] == sid]
    start = 0.0 if i == 0 else round(ss[0]['start_s'] - LEAD, 3)
    scenes.append({'id': sid, 'start': start, 'sentences': [
        {'n': e['n'], 'start': e['start_s'], 'end': e['end_s'], 'text': e['text']} for e in ss]})
for i, s in enumerate(scenes):
    s['end'] = scenes[i + 1]['start'] if i + 1 < len(scenes) else tl['total_s']
    s['dur'] = round(s['end'] - s['start'], 3)
out = {
    '_about': 'C4 animatic timing (generated by src/make_timing.py; do not edit by hand). Absolute seconds on the '
              'narration track. Scenes cut %.2f s before their first sentence. Regenerate from a new voice timeline, '
              'then re-render.' % LEAD,
    'source': os.path.relpath(src, EP), 'audio': tl.get('file'), 'total_s': tl['total_s'], 'fps': 30, 'lead_s': LEAD,
    'scenes': scenes,
    'pauses': [{'kind': p['kind'], 'start': p['start_s'], 'end': p['end_s'], 'dur': p['dur_s'], 'before_n': p.get('before_n')} for p in pauses],
}
json.dump(out, open(os.path.join(AN, 'timing.json'), 'w'), indent=1, ensure_ascii=False)
for s in scenes:
    print(s['id'], f"{s['start']:7.2f} {s['end']:7.2f} {s['dur']:6.2f}s  n{s['sentences'][0]['n']}-{s['sentences'][-1]['n']}")
