#!/usr/bin/env python3
"""Merge src/anchors/Sxx.json (rows: [id, sentence, at, dt, action, meaning with sound off]) into animatic/anchors.json,
resolving each anchor against timing.json the same way the page does (film.js makeT): `at` = 'start' | 'end' | keyword in
the SPOKEN form of the sentence (word timestamps); a keyword not found falls back to its place in the script text, or the
sentence start (reported). Scenes read anchors through T.a(id), so a new voice only needs a new timing.json."""
import glob, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__)); AN = os.path.dirname(HERE)
tm = json.load(open(os.path.join(AN, 'timing.json')))
sent = {s['id']: s for sc in tm['scenes'] for s in sc['sentences']}
start = {sc['id']: sc['start'] for sc in tm['scenes']}
norm = lambda s: [w for w in re.sub(r"[^a-z0-9']+", ' ', s.lower().replace('’', "'")).split() if w]
out = []
for f in sorted(glob.glob(os.path.join(HERE, 'anchors', 'S*.json'))):
    sc = os.path.basename(f)[:3]
    for i, sid, at, dt, act, mean in json.load(open(f)):
        sid = sid if '.' in sid else f'{sc}.{sid}'; s = sent[sid]; found = True
        if at == 'start': t = s['start']
        elif at == 'end': t = s['end']
        else:
            k, w = norm(at), [x['t'] for x in s['words']]
            hit = next((j for j in range(len(w) - len(k) + 1) if w[j:j + len(k)] == k), -1)
            if hit >= 0: t = s['words'][hit]['start']
            else:
                found = False; j = s['text'].lower().find(at.lower())
                t = s['start'] + (s['end'] - s['start']) * j / len(s['text']) if j >= 0 else s['start']
        out.append({'scene': sc, 'id': i, 'sentence': sid, 'at': at, 'dt': dt, 'action': act, 'meaning_muted': mean, 'sentence_text': s['text'],
                    'resolved_s': round(t + dt, 2), 'local_s': round(t + dt - start[sc], 2), 'keyword_found': found})
json.dump({'_about': 'C4 animatic anchor table (generated by src/build_anchors.py from src/anchors/Sxx.json). Every meaningful picture action is tied to a script v5 sentence and a keyword of its spoken form (or its start/end) plus an offset dt; scenes read them through T.a(id), re-resolved from timing.json at render. resolved_s/local_s = where the anchor lands with the current voice; meaning_muted = what the action must say with the sound off.',
           'anchors': out}, open(os.path.join(AN, 'anchors.json'), 'w'), indent=1, ensure_ascii=False)
print(len(out), 'anchors;', sum(not o['keyword_found'] for o in out), 'keywords not found:', [o['scene'] + ':' + o['id'] for o in out if not o['keyword_found']])
