"""C5 audio stream: out/voice/takes.json for the final narration v3.2 (checks/CONTRACT.md: {takes:[{id, raw, final, model?, voiceId?, provider?}], voice}).

    python3 episodes/ep001/work/audio/src/takes.py

One take per scene (G-015 · chọn: one eleven_v3 call per scene), read from work/v32-voice (gen-result.json + takes/<scene>.seed1.json).
raw = the TTS file as returned; final = the same file: the narration was assembled from these takes with gain only, no stretch,
no re-timing (work/v32-voice/src/build.py, out/voice-v32/notes.md), so A13's stretch is 1 by construction.
"""
import json
import os

EP = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
V = os.path.join(EP, 'work', 'v32-voice')


def main():
    gen = json.load(open(os.path.join(V, 'gen-result.json')))
    tl = json.load(open(os.path.join(EP, 'out', 'voice-v32', 'timeline.json')))
    at = {s['scene']: s for s in tl['scenes']}
    takes, models, voices = [], set(), set()
    for sc in sorted(k for k in gen if '@' not in k):  # 'S18@r1' = take cũ đã thay (30/09), không dùng
        use = gen[sc]['use']
        meta = json.load(open(os.path.join(V, 'takes', use[:-4] + '.json')))
        models.add(meta['model'])
        voices.add(meta['voice'])
        rel = f'work/v32-voice/takes/{use}'
        assert os.path.exists(os.path.join(EP, rel)), rel
        takes.append({'id': sc, 'raw': rel, 'final': rel, 'model': meta['model'], 'voiceId': meta['voice'], 'provider': 'elevenlabs',
                      'seed': meta.get('seed'), 'sentences': gen[sc]['n'], 'startInNarration': at[sc]['start_s'], 'durS': at[sc]['dur_s'],
                      'tags': gen[sc].get('tags') or {}})
    assert len(models) == 1 and len(voices) == 1, (models, voices)
    out = {'_about': 'Narration v3.2 (final, owner-approved at C4): one eleven_v3 take per scene, Eric, default settings, no speed, no stretch. '
                     'raw = final (gain only in assembly: work/v32-voice/src/build.py). Generated by work/audio/src/takes.py.',
           'narration': 'review-c4/narration-v32.m4a', 'takes': takes,
           'voice': {'provider': 'elevenlabs', 'voiceId': voices.pop(), 'model': models.pop(), 'name': 'Eric (premade)', 'settings': 'default (no speed, no voice_settings)'}}
    os.makedirs(os.path.join(EP, 'out', 'voice'), exist_ok=True)
    json.dump(out, open(os.path.join(EP, 'out', 'voice', 'takes.json'), 'w'), indent=1, ensure_ascii=False)
    print(len(takes), 'takes', out['voice'])


if __name__ == '__main__':
    main()
